# TODO : Créer un script Python pour saisir et publier des découvertes planétaires sur un blog intergalactique.

planete = input("Entrez le nom de la planete exploree: ")
date_visite = ...
description = ...
